name: finance_api
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  dotenv: ^4.2.0
  orm: ^5.2.0
  crypto: ^3.0.5
  dart_jsonwebtoken: ^2.14.1
  redis: ^4.0.0
  dart_frog_cors: ^2.0.0
  zod_validation: ^1.0.5

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
